# Generated by Django 4.1.2 on 2022-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mip_dr_app_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cellmethods",
            options={
                "verbose_name": "7.1 Cell Methods",
                "verbose_name_plural": "7.1 Cell Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="cmorvar",
            options={
                "verbose_name": "1.3 CMOR Variable",
                "verbose_name_plural": "1.3 CMOR Variable",
            },
        ),
        migrations.AlterModelOptions(
            name="experiment",
            options={
                "verbose_name": "1.5 Experiments",
                "verbose_name_plural": "1.5 Experiments",
            },
        ),
        migrations.AlterModelOptions(
            name="exptgroup",
            options={
                "verbose_name": "1.9 Experiment Group",
                "verbose_name_plural": "1.9 Experiment Group",
            },
        ),
        migrations.AlterModelOptions(
            name="grids",
            options={
                "verbose_name": "1.7 Specification of dimensions",
                "verbose_name_plural": "1.7 Specification of dimensions",
            },
        ),
        migrations.AlterModelOptions(
            name="mip",
            options={
                "verbose_name": "1.1 Model Intercomparison Project",
                "verbose_name_plural": "1.1 Model Intercomparison Project",
            },
        ),
        migrations.AlterModelOptions(
            name="miptable",
            options={
                "verbose_name": "2.4 MIP tables",
                "verbose_name_plural": "2.4 MIP tables",
            },
        ),
        migrations.AlterModelOptions(
            name="modelconfig",
            options={
                "verbose_name": "3.5 Model configuration options",
                "verbose_name_plural": "3.5 Model configuration options",
            },
        ),
        migrations.AlterModelOptions(
            name="objective",
            options={
                "verbose_name": "1.6 Scientific objectives",
                "verbose_name_plural": "1.6 Scientific objectives",
            },
        ),
        migrations.AlterModelOptions(
            name="objectivelink",
            options={
                "verbose_name": "3.7 Link between scientific objectives and requests",
                "verbose_name_plural": "3.7 Link between scientific objectives and requests",
            },
        ),
        migrations.AlterModelOptions(
            name="places",
            options={
                "verbose_name": "Places, States or Reservoirs",
                "verbose_name_plural": "Places, States or Reservoirs",
            },
        ),
        migrations.AlterModelOptions(
            name="qcranges",
            options={
                "verbose_name": "Quality Control Ranges",
                "verbose_name_plural": "Quality Control Ranges",
            },
        ),
        migrations.AlterModelOptions(
            name="remarks",
            options={
                "verbose_name": "3.8 Remarks about other items",
                "verbose_name_plural": "3.8 Remarks about other items",
            },
        ),
        migrations.AlterModelOptions(
            name="requestitem",
            options={
                "verbose_name": "3.2 Request Item: specifying the number of years for an experiment",
                "verbose_name_plural": "3.2 Request Item: specifying the number of years for an experiment",
            },
        ),
        migrations.AlterModelOptions(
            name="requestlink",
            options={
                "verbose_name": "3.3 Request link: linking a set of variables and a set of experiments",
                "verbose_name_plural": "3.3 Request link: linking a set of variables and a set of experiments",
            },
        ),
        migrations.AlterModelOptions(
            name="requestvar",
            options={
                "verbose_name": "1.4 Request variable (carrying priority and link to group)",
                "verbose_name_plural": "1.4 Request variable (carrying priority and link to group)",
            },
        ),
        migrations.AlterModelOptions(
            name="requestvargroup",
            options={
                "verbose_name": "3.1 Request variable group: a collection of request variables",
                "verbose_name_plural": "3.1 Request variable group: a collection of request variables",
            },
        ),
        migrations.AlterModelOptions(
            name="spatialshape",
            options={
                "verbose_name": "2.1 Spatial dimensions",
                "verbose_name_plural": "2.1 Spatial dimensions",
            },
        ),
        migrations.AlterModelOptions(
            name="standardname",
            options={
                "verbose_name": "1.8 CF Standard Names",
                "verbose_name_plural": "1.8 CF Standard Names",
            },
        ),
        migrations.AlterModelOptions(
            name="structure",
            options={
                "verbose_name": "2.3 Dimensions and related information",
                "verbose_name_plural": "2.3 Dimensions and related information",
            },
        ),
        migrations.AlterModelOptions(
            name="tablesection",
            options={
                "verbose_name": "3.4 CMOR Table Sections",
                "verbose_name_plural": "3.4 CMOR Table Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="temporalshape",
            options={
                "verbose_name": "2.2 Temporal dimension",
                "verbose_name_plural": "2.2 Temporal dimension",
            },
        ),
        migrations.AlterModelOptions(
            name="timeslice",
            options={
                "verbose_name": "3.11 Time Slices for Output Requests",
                "verbose_name_plural": "3.11 Time Slices for Output Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="transfers",
            options={
                "verbose_name": "Transfers of Material",
                "verbose_name_plural": "Transfers of Material",
            },
        ),
        migrations.AlterModelOptions(
            name="units",
            options={"verbose_name": "Units", "verbose_name_plural": "Units"},
        ),
        migrations.AlterModelOptions(
            name="var",
            options={
                "verbose_name": "1.2 MIP Variable",
                "verbose_name_plural": "1.2 MIP Variable",
            },
        ),
        migrations.AlterModelOptions(
            name="varchoice",
            options={
                "verbose_name": "3.10 Indicates variables for which a there is a range of potential CMOR Variables",
                "verbose_name_plural": "3.10 Indicates variables for which a there is a range of potential CMOR Variables",
            },
        ),
        migrations.AlterModelOptions(
            name="varchoicelinkc",
            options={
                "verbose_name": "3.6 Links a variable to a choice element",
                "verbose_name_plural": "3.6 Links a variable to a choice element",
            },
        ),
        migrations.AlterModelOptions(
            name="varchoicelinkr",
            options={
                "verbose_name": "3.9 Links a variable to a choice element",
                "verbose_name_plural": "3.9 Links a variable to a choice element",
            },
        ),
        migrations.AddField(
            model_name="cellmethods",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cellmethods",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cmorvar",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cmorvar",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experiment",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="experiment",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exptgroup",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="exptgroup",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grids",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="grids",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mip",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mip",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="miptable",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="miptable",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objective",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="objective",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectivelink",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="objectivelink",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="places",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="places",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qcranges",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="qcranges",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="remarks",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="remarks",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestitem",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestitem",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestlink",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestlink",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestvar",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestvar",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestvargroup",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestvargroup",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spatialshape",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="spatialshape",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standardname",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="standardname",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="structure",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tablesection",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tablesection",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="temporalshape",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="temporalshape",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslice",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="timeslice",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfers",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transfers",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="units",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="units",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="var",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="var",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="varchoice",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="varchoice",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="varchoicelinkc",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="varchoicelinkc",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="varchoicelinkr",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="varchoicelinkr",
            name="date_published",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
