"""
This resource.py file was generated by the script generate_models_from_xml.py

"""
from import_export import resources

from mip_dr_app_vocab import models


class UnitsResource(resources.ModelResource):
    class Meta:
        model = models.Units
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class MiptableResource(resources.ModelResource):
    class Meta:
        model = models.Miptable
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class MipResource(resources.ModelResource):
    class Meta:
        model = models.Mip
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class RequestVarGroupResource(resources.ModelResource):
    class Meta:
        model = models.RequestVarGroup
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class ExptgroupResource(resources.ModelResource):
    class Meta:
        model = models.Exptgroup
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class RequestLinkResource(resources.ModelResource):
    class Meta:
        model = models.RequestLink
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class ExperimentResource(resources.ModelResource):
    class Meta:
        model = models.Experiment
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class GridsResource(resources.ModelResource):
    class Meta:
        model = models.Grids
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class RequestItemResource(resources.ModelResource):
    class Meta:
        model = models.RequestItem
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class ObjectiveResource(resources.ModelResource):
    class Meta:
        model = models.Objective
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class SpatialShapeResource(resources.ModelResource):
    class Meta:
        model = models.SpatialShape
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class ModelConfigResource(resources.ModelResource):
    class Meta:
        model = models.ModelConfig
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class ObjectiveLinkResource(resources.ModelResource):
    class Meta:
        model = models.ObjectiveLink
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class RemarksResource(resources.ModelResource):
    class Meta:
        model = models.Remarks
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class StandardnameResource(resources.ModelResource):
    class Meta:
        model = models.Standardname
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class VarResource(resources.ModelResource):
    class Meta:
        model = models.Var
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class VarChoiceResource(resources.ModelResource):
    class Meta:
        model = models.VarChoice
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class TemporalShapeResource(resources.ModelResource):
    class Meta:
        model = models.TemporalShape
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class TimeSliceResource(resources.ModelResource):
    class Meta:
        model = models.TimeSlice
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class CellMethodsResource(resources.ModelResource):
    class Meta:
        model = models.CellMethods
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class StructureResource(resources.ModelResource):
    class Meta:
        model = models.Structure
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class CMORvarResource(resources.ModelResource):
    class Meta:
        model = models.CMORvar
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class VarChoiceLinkCResource(resources.ModelResource):
    class Meta:
        model = models.VarChoiceLinkC
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class RequestVarResource(resources.ModelResource):
    class Meta:
        model = models.RequestVar
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class VarChoiceLinkRResource(resources.ModelResource):
    class Meta:
        model = models.VarChoiceLinkR
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class TableSectionResource(resources.ModelResource):
    class Meta:
        model = models.TableSection
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class QcrangesResource(resources.ModelResource):
    class Meta:
        model = models.Qcranges
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class PlacesResource(resources.ModelResource):
    class Meta:
        model = models.Places
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


class TransfersResource(resources.ModelResource):
    class Meta:
        model = models.Transfers
        import_id_fields = ('uid',)
        skip_unchanged = True
        report_skipped = True


def get_resource(name):
    if name == "Units":
        return UnitsResource()
    if name == "Miptable":
        return MiptableResource()
    if name == "Mip":
        return MipResource()
    if name == "RequestVarGroup":
        return RequestVarGroupResource()
    if name == "Exptgroup":
        return ExptgroupResource()
    if name == "RequestLink":
        return RequestLinkResource()
    if name == "Experiment":
        return ExperimentResource()
    if name == "Grids":
        return GridsResource()
    if name == "RequestItem":
        return RequestItemResource()
    if name == "Objective":
        return ObjectiveResource()
    if name == "SpatialShape":
        return SpatialShapeResource()
    if name == "ModelConfig":
        return ModelConfigResource()
    if name == "ObjectiveLink":
        return ObjectiveLinkResource()
    if name == "Remarks":
        return RemarksResource()
    if name == "Standardname":
        return StandardnameResource()
    if name == "Var":
        return VarResource()
    if name == "VarChoice":
        return VarChoiceResource()
    if name == "TemporalShape":
        return TemporalShapeResource()
    if name == "TimeSlice":
        return TimeSliceResource()
    if name == "CellMethods":
        return CellMethodsResource()
    if name == "Structure":
        return StructureResource()
    if name == "CMORvar":
        return CMORvarResource()
    if name == "VarChoiceLinkC":
        return VarChoiceLinkCResource()
    if name == "RequestVar":
        return RequestVarResource()
    if name == "VarChoiceLinkR":
        return VarChoiceLinkRResource()
    if name == "TableSection":
        return TableSectionResource()
    if name == "Qcranges":
        return QcrangesResource()
    if name == "Places":
        return PlacesResource()
    if name == "Transfers":
        return TransfersResource()
